#!/usr/bin/python3
""" This module defines the Base class. """
import json


class Base:
    """ Base class for managing unique IDs. """

    __nb_objects = 0

    def __init__(self, id=None):
        """
        Initializes an instance of the Base class.

        Args:
            id (int): The unique identifier for the instance.

        Attributes:
            id (int): The unique identifier for the instance.

        If `id` is provided it will be assigned to instance's `id` attribute
        If `id` is not provided it will be automatically generated by
        incrementing
        private class attribute __nb_objects and assigned to instance's `id`
        """
        if id is not None:
            self.id = id
        else:
            Base.__nb_objects += 1
            self.id = Base.__nb_objects

    @staticmethod
    def to_json_string(list_dictionaries):
        """
        Return the JSON string representation of list_dictionaries.

        Args:
            list_dictionaries (list): A list of dictionaries.

        Returns:
            str: JSON string representation of the list of dictionaries.
        """
        if list_dictionaries is None or len(list_dictionaries) == 0:
            return "[]"
        return json.dumps(list_dictionaries)
