#!/usr/bin/python3
""" This module defines the Base class. """


class Base:
    """ Base class for managing unique IDs. """

    __nb_objects = 0

    def __init__(self, id=None):
        """
        Initializes an instance of the Base class.

        Args:
            id (int): The unique identifier for the instance.

        Attributes:
            id (int): The unique identifier for the instance.

        If `id` is provided, it will be assigned to the instance's `id` attribute.
        If `id` is not provided, it will be automatically generated by incrementing
        the private class attribute __nb_objects and assigned to the instance's `id`.
        """
        if id is not None:
            self.id = id
        else:
            Base.__nb_objects += 1
            self.id = Base.__nb_objects
